### ISSUE TITLE
ListSubscribe returns an error on 204 status codes

### ISSUE THREAD

**Issue by vince-makelog** [trycourier/courier-go#26]
## Expected Behavior

Should not return an error, unless the status code is >=4xx

## Actual Behavior

The library https://github.com/trycourier/courier-go/blob/master/v2/api.go#L112 returns an error for anything that's not a 200.

## Steps to Reproduce the Problem

  1. Use ListSubscribe
  1. API returns 204
  1. Library returns an error

## Specifications

  - Version: v2

**Comment by tk26** [comment]
@vince-makelog we've fixed the issue. Thanks for the feedback.
