### ISSUE TITLE
Can we expose a retry mechanism for retryable http failures

### ISSUE THREAD

**Issue by niqbal** [trycourier/courier-go#48]
## Expected Behavior
Since the http request to courier can occasionally fail due to intermittent issues (network issue, rate-limiting, etc) it will be helpful if the client api exposes an option to retry the request after some backoff. 

## Actual Behavior
The issue hasn't happened to me but I will be nice to have if there is a retry mechanism. Meanwhile, I will use something like: https://github.com/cenkalti/backoff to retry the failures. 

## Steps to Reproduce the Problem
  1
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by dsinghvi** [comment]
Hey @niqbal  -- Courier now uses [Fern](https://buildwithfern.com/) to generate its SDKs. As part of this we have released a v3 of the Go SDK that includes expoenential backoff and retry!
